"""Add NPC-Location and Location-Location link tables

Revision ID: 125f1dcfdbd2
Revises: 40c8948b4399
Create Date: 2026-02-22 07:31:22.462657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '125f1dcfdbd2'
down_revision = '40c8948b4399'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location_connection',
    sa.Column('location_a_id', sa.Integer(), nullable=False),
    sa.Column('location_b_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['location_a_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['location_b_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('location_a_id', 'location_b_id')
    )
    op.create_table('npc_location_link',
    sa.Column('npc_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['npc_id'], ['npcs.id'], ),
    sa.PrimaryKeyConstraint('npc_id', 'location_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('npc_location_link')
    op.drop_table('location_connection')
    # ### end Alembic commands ###
