"""add adventure builder models

Revision ID: 4fe4af6006d0
Revises: p6q7r8s9t0u1
Create Date: 2026-03-11 08:49:46.316600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fe4af6006d0'
down_revision = 'p6q7r8s9t0u1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adventure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('tagline', sa.String(length=300), nullable=True),
    sa.Column('concept', sa.Text(), nullable=True),
    sa.Column('synopsis', sa.Text(), nullable=True),
    sa.Column('hook', sa.Text(), nullable=True),
    sa.Column('premise', sa.Text(), nullable=True),
    sa.Column('system_hint', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('is_player_visible', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('adventure_act',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('adventure_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['adventure_id'], ['adventure.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('adventure_faction_link',
    sa.Column('adventure_id', sa.Integer(), nullable=False),
    sa.Column('faction_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['adventure_id'], ['adventure.id'], ),
    sa.ForeignKeyConstraint(['faction_id'], ['factions.id'], ),
    sa.PrimaryKeyConstraint('adventure_id', 'faction_id')
    )
    op.create_table('adventure_scene',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('act_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('scene_type', sa.String(length=50), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['act_id'], ['adventure_act.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('adventure_npc_link',
    sa.Column('adventure_id', sa.Integer(), nullable=False),
    sa.Column('npc_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['adventure_id'], ['adventure.id'], ),
    sa.ForeignKeyConstraint(['npc_id'], ['npcs.id'], ),
    sa.PrimaryKeyConstraint('adventure_id', 'npc_id')
    )
    op.create_table('adventure_room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scene_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=10), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('read_aloud', sa.Text(), nullable=True),
    sa.Column('gm_notes', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['scene_id'], ['adventure_scene.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('room_creature',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('hearts', sa.Integer(), nullable=True),
    sa.Column('effort_type', sa.String(length=20), nullable=True),
    sa.Column('special_move', sa.String(length=500), nullable=True),
    sa.Column('timer_rounds', sa.Integer(), nullable=True),
    sa.Column('hp', sa.Integer(), nullable=True),
    sa.Column('ac', sa.Integer(), nullable=True),
    sa.Column('cr', sa.String(length=10), nullable=True),
    sa.Column('actions', sa.Text(), nullable=True),
    sa.Column('bestiary_entry_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bestiary_entry_id'], ['bestiary_entries.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['adventure_room.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('room_hazard',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('dc_or_target', sa.String(length=50), nullable=True),
    sa.Column('consequence', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['adventure_room.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('room_loot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('loot_def_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['loot_def_id'], ['icrpg_loot_defs.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['adventure_room.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('room_loot')
    op.drop_table('room_hazard')
    op.drop_table('room_creature')
    op.drop_table('adventure_room')
    op.drop_table('adventure_npc_link')
    op.drop_table('adventure_scene')
    op.drop_table('adventure_faction_link')
    op.drop_table('adventure_act')
    op.drop_table('adventure')
    # ### end Alembic commands ###
