"""Add portrait_filename to NPC and map_filename to Location

Revision ID: 53e096b2ae3c
Revises: 7b647ebc96fd
Create Date: 2026-02-22 18:23:25.747316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53e096b2ae3c'
down_revision = '7b647ebc96fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('map_filename', sa.String(length=255), nullable=True))

    with op.batch_alter_table('npcs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('portrait_filename', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('npcs', schema=None) as batch_op:
        batch_op.drop_column('portrait_filename')

    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.drop_column('map_filename')

    # ### end Alembic commands ###
