"""Add session attendance and session mode fields

Revision ID: ad6dbe59ded3
Revises: ec2777fca4b2
Create Date: 2026-02-22 19:17:19.803498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad6dbe59ded3'
down_revision = 'ec2777fca4b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['player_characters.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pinned_npc_ids', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('active_location_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_sessions_active_location_id', 'locations', ['active_location_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_sessions_active_location_id', type_='foreignkey')
        batch_op.drop_column('active_location_id')
        batch_op.drop_column('pinned_npc_ids')

    op.drop_table('session_attendance')
    # ### end Alembic commands ###
