"""Add Item model

Revision ID: e0cf9d7c2be2
Revises: 5e6202444694
Create Date: 2026-02-22 07:51:04.299549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0cf9d7c2be2'
down_revision = '5e6202444694'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('rarity', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('gm_notes', sa.Text(), nullable=True),
    sa.Column('is_player_visible', sa.Boolean(), nullable=True),
    sa.Column('owner_npc_id', sa.Integer(), nullable=True),
    sa.Column('origin_location_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['origin_location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['owner_npc_id'], ['npcs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('items')
    # ### end Alembic commands ###
