"""Add PlayerCharacter and PlayerCharacterStat models

Revision ID: ec2777fca4b2
Revises: 3d6b9a9dc537
Create Date: 2026-02-22 19:12:37.468391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec2777fca4b2'
down_revision = '3d6b9a9dc537'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('character_name', sa.String(length=200), nullable=False),
    sa.Column('player_name', sa.String(length=200), nullable=False),
    sa.Column('level_or_rank', sa.String(length=100), nullable=True),
    sa.Column('class_or_role', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('portrait_filename', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_character_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('template_field_id', sa.Integer(), nullable=False),
    sa.Column('stat_value', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['player_characters.id'], ),
    sa.ForeignKeyConstraint(['template_field_id'], ['campaign_stat_template.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_character_stats')
    op.drop_table('player_characters')
    # ### end Alembic commands ###
